$(document).ready(function(){
    $('#searchbar').hide();
    $("#facebook").click(function(){
        $(".twp").hide();
        $(".np").hide();
        $(".fbp").show();
        $('#searchbar').hide();
    });
    $("#twitter").click(function(){
        $(".fbp").hide();
        $(".np").hide();
        $(".twp").show();
        $('#searchbar').hide();
    });
    $("#news").click(function(){
        $(".fbp").hide();
        $(".twp").hide();
        $(".np").show();
        $('#searchbar').show();
    });
    $("#home").click(function(){
        $(".fbp").show();
        $(".twp").show();
        $(".np").show();
        $('#searchbar').hide();
    });
});
